### ISSUE TITLE
images inside text

### ISSUE THREAD

**Issue by nick-mccomb-easygo** [IslamRustamov/-react-native-rich-text-input#1]
Can this do images inside the text?  For example, for having emotes in a chat application alongside the text

**Comment by IslamRustamov** [comment]
Hi

I was not planning on adding images to this text editor, since I wanted this editor to be more Telegram-styled.

But if you share some examples with me of how other rich text editors handle images, maybe I will think about working on that

**Comment by IslamRustamov** [comment]
If we are talking about emotes - I will take a look into that. But for now I think adding links feature has more priority

**Comment by IslamRustamov** [comment]
Closing this issue since I thought that this should be a TEXT INPUT that copies Telegram's text input, not a TEXT EDITOR. Emotes, images and stuff should be dealt with separately from this library
